/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Right_Eyeball.h"
#include "Right_Eyeball_Pan_aliases.h"
#include "Right_Eyeball_Pan.h"
#include "Right_Eyeball_Tilt_aliases.h"
#include "Right_Eyeball_Tilt.h"
#include "Clock_1.h"
#include "Left_Eyeball.h"
#include "Left_Eyeball_Tilt_aliases.h"
#include "Left_Eyeball_Tilt.h"
#include "Left_Eyeball_Pan_aliases.h"
#include "Left_Eyeball_Pan.h"
#include "Clock_2.h"
#include "Right_Eyebrow.h"
#include "Right_Eyebrow_Pan_aliases.h"
#include "Right_Eyebrow_Pan.h"
#include "Right_Eyebrow_Tilt_aliases.h"
#include "Right_Eyebrow_Tilt.h"
#include "Clock_3.h"
#include "Left_Eyebrow.h"
#include "Clock_4.h"
#include "Left_Eyebrow_Pan_aliases.h"
#include "Left_Eyebrow_Pan.h"
#include "Left_Eyebrow_Tilt_aliases.h"
#include "Left_Eyebrow_Tilt.h"
#include "NeckHandle.h"
#include "NeckHandle_Right_aliases.h"
#include "NeckHandle_Right.h"
#include "NeckHandle_Left_aliases.h"
#include "NeckHandle_Left.h"
#include "Clock_5.h"
#include "Upper_Lips.h"
#include "Upper_Lips_Left_aliases.h"
#include "Upper_Lips_Left.h"
#include "Upper_Lips_Right_aliases.h"
#include "Upper_Lips_Right.h"
#include "Clock_6.h"
#include "Clock_7.h"
#include "Lower_Lips_Left_aliases.h"
#include "Lower_Lips_Left.h"
#include "Lower_Lips_Right_aliases.h"
#include "Lower_Lips_Right.h"
#include "Lower_Lips.h"
#include "Clock_8.h"
#include "Eye_Rod_1_aliases.h"
#include "Eye_Rod_1.h"
#include "Eye_Rod_2_aliases.h"
#include "Eye_Rod_2.h"
#include "Eye_Rod.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

